version: '3'
services:
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
      - "3000:3000"
      depends_on:
      - db
      container_name: tm-frontend
      volumes:
       - ./frontend:/var/www/
       - /var/www/node_modules
  backend:
      container_name: tm-backend
      restart: on-failure
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager
        SPRING_DATASOURCE_USERNAME: sisi
        SPRING_DATASOURCE_PASSWORD: password
      depends_on:
      - db
      build:
         context: ./backend
         dockerfile: Dockerfile
      ports:
      - "8080:8080"
      volumes:
      - ./backend/build/libs/:/app/
  db:
      container_name: bct-db
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: sisi
        POSTGRES_DB: task_manager
      ports:
        - "5432:5432"
      image: 'postgres:13.1-alpine'
      volumes:
        - dbdata:/var/lib/postgresql/data
  nginx:
    container_name: tm-proxy
    depends_on:
      - frontend
      - backend
    restart: always
    volumes:
     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "3001:80"
volumes:
    dbdata:

